development:
  sessions:
    default:
      database: Grupo03
      hosts:
        - localhost:27017
      options:
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false
test:
  sessions:
    default:
      database: Grupo03
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false
staging:
  sessions:
    default:
      database: Grupo03
      hosts:
        - localhost:27017
      options:
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false
production:
  sessions:
    default:
      database: Grupo03
      hosts:
        - localhost:27017
      options:
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false